export type LeetCodeDifficulty = "简单" | "中等" | "困难";

export type LeetCodeProblem = {
  id: number;
  title: string;
  slug: string;
  difficulty: LeetCodeDifficulty;
  tags: string[];
  url: string;
};

const createProblem = (
  id: number,
  title: string,
  slug: string,
  difficulty: LeetCodeDifficulty,
  tags: string[],
): LeetCodeProblem => ({
  id,
  title,
  slug,
  difficulty,
  tags,
  url: `https://leetcode.cn/problems/${slug}/`,
});

export const LEETCODE_HOT_100_PROBLEMS = [
  createProblem(1, "两数之和", "two-sum", "简单", ["数组", "哈希表"]),
  createProblem(2, "两数相加", "add-two-numbers", "中等", ["链表", "数学"]),
  createProblem(3, "无重复字符的最长子串", "longest-substring-without-repeating-characters", "中等", ["哈希表", "滑动窗口"]),
  createProblem(4, "寻找两个正序数组的中位数", "median-of-two-sorted-arrays", "困难", ["数组", "二分查找"]),
  createProblem(5, "最长回文子串", "longest-palindromic-substring", "中等", ["字符串", "动态规划"]),
  createProblem(11, "盛最多水的容器", "container-with-most-water", "中等", ["数组", "双指针", "贪心"]),
  createProblem(15, "三数之和", "3sum", "中等", ["数组", "双指针", "排序"]),
  createProblem(17, "电话号码的字母组合", "letter-combinations-of-a-phone-number", "中等", ["回溯", "字符串"]),
  createProblem(19, "删除链表的倒数第 N 个结点", "remove-nth-node-from-end-of-list", "中等", ["链表", "双指针"]),
  createProblem(20, "有效的括号", "valid-parentheses", "简单", ["栈", "字符串"]),
  createProblem(21, "合并两个有序链表", "merge-two-sorted-lists", "简单", ["链表", "递归"]),
  createProblem(22, "括号生成", "generate-parentheses", "中等", ["回溯", "字符串"]),
  createProblem(23, "合并 K 个升序链表", "merge-k-sorted-lists", "困难", ["链表", "堆"]),
  createProblem(24, "两两交换链表中的节点", "swap-nodes-in-pairs", "中等", ["链表", "递归"]),
  createProblem(25, "K 个一组翻转链表", "reverse-nodes-in-k-group", "困难", ["链表", "递归"]),
  createProblem(31, "下一个排列", "next-permutation", "中等", ["数组", "双指针"]),
  createProblem(32, "最长有效括号", "longest-valid-parentheses", "困难", ["栈", "动态规划"]),
  createProblem(33, "搜索旋转排序数组", "search-in-rotated-sorted-array", "中等", ["数组", "二分查找"]),
  createProblem(34, "在排序数组中查找元素的第一个和最后一个位置", "find-first-and-last-position-of-element-in-sorted-array", "中等", ["数组", "二分查找"]),
  createProblem(35, "搜索插入位置", "search-insert-position", "简单", ["数组", "二分查找"]),
  createProblem(39, "组合总和", "combination-sum", "中等", ["数组", "回溯"]),
  createProblem(41, "缺失的第一个正数", "first-missing-positive", "困难", ["数组", "哈希表"]),
  createProblem(42, "接雨水", "trapping-rain-water", "困难", ["数组", "双指针", "单调栈"]),
  createProblem(46, "全排列", "permutations", "中等", ["数组", "回溯"]),
  createProblem(48, "旋转图像", "rotate-image", "中等", ["数组", "矩阵"]),
  createProblem(49, "字母异位词分组", "group-anagrams", "中等", ["哈希表", "字符串"]),
  createProblem(51, "N 皇后", "n-queens", "困难", ["回溯"]),
  createProblem(53, "最大子数组和", "maximum-subarray", "中等", ["数组", "动态规划"]),
  createProblem(54, "螺旋矩阵", "spiral-matrix", "中等", ["数组", "矩阵"]),
  createProblem(55, "跳跃游戏", "jump-game", "中等", ["数组", "贪心"]),
  createProblem(56, "合并区间", "merge-intervals", "中等", ["数组", "排序"]),
  createProblem(62, "不同路径", "unique-paths", "中等", ["数学", "动态规划"]),
  createProblem(64, "最小路径和", "minimum-path-sum", "中等", ["数组", "动态规划"]),
  createProblem(70, "爬楼梯", "climbing-stairs", "简单", ["动态规划"]),
  createProblem(72, "编辑距离", "edit-distance", "中等", ["字符串", "动态规划"]),
  createProblem(73, "矩阵置零", "set-matrix-zeroes", "中等", ["数组", "矩阵"]),
  createProblem(74, "搜索二维矩阵", "search-a-2d-matrix", "中等", ["数组", "二分查找"]),
  createProblem(75, "颜色分类", "sort-colors", "中等", ["数组", "双指针", "排序"]),
  createProblem(76, "最小覆盖子串", "minimum-window-substring", "困难", ["哈希表", "滑动窗口"]),
  createProblem(78, "子集", "subsets", "中等", ["数组", "回溯"]),
  createProblem(79, "单词搜索", "word-search", "中等", ["数组", "回溯", "矩阵"]),
  createProblem(84, "柱状图中最大的矩形", "largest-rectangle-in-histogram", "困难", ["栈", "单调栈"]),
  createProblem(94, "二叉树的中序遍历", "binary-tree-inorder-traversal", "简单", ["树", "深度优先搜索"]),
  createProblem(96, "不同的二叉搜索树", "unique-binary-search-trees", "中等", ["树", "动态规划"]),
  createProblem(98, "验证二叉搜索树", "validate-binary-search-tree", "中等", ["树", "深度优先搜索"]),
  createProblem(101, "对称二叉树", "symmetric-tree", "简单", ["树", "广度优先搜索"]),
  createProblem(102, "二叉树的层序遍历", "binary-tree-level-order-traversal", "中等", ["树", "广度优先搜索"]),
  createProblem(104, "二叉树的最大深度", "maximum-depth-of-binary-tree", "简单", ["树", "深度优先搜索"]),
  createProblem(105, "从前序与中序遍历序列构造二叉树", "construct-binary-tree-from-preorder-and-inorder-traversal", "中等", ["树", "数组", "哈希表"]),
  createProblem(108, "将有序数组转换为二叉搜索树", "convert-sorted-array-to-binary-search-tree", "简单", ["树", "二分查找"]),
  createProblem(114, "二叉树展开为链表", "flatten-binary-tree-to-linked-list", "中等", ["树", "深度优先搜索"]),
  createProblem(118, "杨辉三角", "pascals-triangle", "简单", ["数组", "动态规划"]),
  createProblem(121, "买卖股票的最佳时机", "best-time-to-buy-and-sell-stock", "简单", ["数组", "动态规划"]),
  createProblem(124, "二叉树中的最大路径和", "binary-tree-maximum-path-sum", "困难", ["树", "动态规划"]),
  createProblem(128, "最长连续序列", "longest-consecutive-sequence", "中等", ["数组", "哈希表"]),
  createProblem(131, "分割回文串", "palindrome-partitioning", "中等", ["字符串", "回溯"]),
  createProblem(136, "只出现一次的数字", "single-number", "简单", ["位运算", "数组"]),
  createProblem(138, "随机链表的复制", "copy-list-with-random-pointer", "中等", ["哈希表", "链表"]),
  createProblem(139, "单词拆分", "word-break", "中等", ["字典树", "动态规划"]),
  createProblem(141, "环形链表", "linked-list-cycle", "简单", ["链表", "双指针"]),
  createProblem(142, "环形链表 II", "linked-list-cycle-ii", "中等", ["链表", "双指针"]),
  createProblem(146, "LRU 缓存", "lru-cache", "中等", ["哈希表", "链表"]),
  createProblem(148, "排序链表", "sort-list", "中等", ["链表", "排序"]),
  createProblem(152, "乘积最大子数组", "maximum-product-subarray", "中等", ["数组", "动态规划"]),
  createProblem(153, "寻找旋转排序数组中的最小值", "find-minimum-in-rotated-sorted-array", "中等", ["数组", "二分查找"]),
  createProblem(155, "最小栈", "min-stack", "中等", ["栈", "设计"]),
  createProblem(160, "相交链表", "intersection-of-two-linked-lists", "简单", ["哈希表", "链表"]),
  createProblem(169, "多数元素", "majority-element", "简单", ["数组", "计数"]),
  createProblem(189, "轮转数组", "rotate-array", "中等", ["数组", "数学"]),
  createProblem(198, "打家劫舍", "house-robber", "中等", ["数组", "动态规划"]),
  createProblem(199, "二叉树的右视图", "binary-tree-right-side-view", "中等", ["树", "广度优先搜索"]),
  createProblem(200, "岛屿数量", "number-of-islands", "中等", ["深度优先搜索", "广度优先搜索", "矩阵"]),
  createProblem(206, "反转链表", "reverse-linked-list", "简单", ["链表", "递归"]),
  createProblem(207, "课程表", "course-schedule", "中等", ["图", "拓扑排序"]),
  createProblem(208, "实现 Trie", "implement-trie-prefix-tree", "中等", ["设计", "字典树"]),
  createProblem(215, "数组中的第 K 个最大元素", "kth-largest-element-in-an-array", "中等", ["数组", "快速选择", "堆"]),
  createProblem(226, "翻转二叉树", "invert-binary-tree", "简单", ["树", "深度优先搜索"]),
  createProblem(230, "二叉搜索树中第 K 小的元素", "kth-smallest-element-in-a-bst", "中等", ["树", "深度优先搜索"]),
  createProblem(234, "回文链表", "palindrome-linked-list", "简单", ["链表", "双指针"]),
  createProblem(236, "二叉树的最近公共祖先", "lowest-common-ancestor-of-a-binary-tree", "中等", ["树", "深度优先搜索"]),
  createProblem(238, "除自身以外数组的乘积", "product-of-array-except-self", "中等", ["数组", "前缀和"]),
  createProblem(239, "滑动窗口最大值", "sliding-window-maximum", "困难", ["队列", "滑动窗口"]),
  createProblem(240, "搜索二维矩阵 II", "search-a-2d-matrix-ii", "中等", ["数组", "二分查找", "矩阵"]),
  createProblem(279, "完全平方数", "perfect-squares", "中等", ["动态规划", "数学"]),
  createProblem(283, "移动零", "move-zeroes", "简单", ["数组", "双指针"]),
  createProblem(287, "寻找重复数", "find-the-duplicate-number", "中等", ["数组", "双指针"]),
  createProblem(295, "数据流的中位数", "find-median-from-data-stream", "困难", ["设计", "堆"]),
  createProblem(300, "最长递增子序列", "longest-increasing-subsequence", "中等", ["数组", "动态规划"]),
  createProblem(322, "零钱兑换", "coin-change", "中等", ["动态规划", "广度优先搜索"]),
  createProblem(347, "前 K 个高频元素", "top-k-frequent-elements", "中等", ["哈希表", "堆"]),
  createProblem(394, "字符串解码", "decode-string", "中等", ["栈", "字符串"]),
  createProblem(416, "分割等和子集", "partition-equal-subset-sum", "中等", ["数组", "动态规划"]),
  createProblem(437, "路径总和 III", "path-sum-iii", "中等", ["树", "深度优先搜索"]),
  createProblem(438, "找到字符串中所有字母异位词", "find-all-anagrams-in-a-string", "中等", ["哈希表", "滑动窗口"]),
  createProblem(543, "二叉树的直径", "diameter-of-binary-tree", "简单", ["树", "深度优先搜索"]),
  createProblem(560, "和为 K 的子数组", "subarray-sum-equals-k", "中等", ["数组", "前缀和", "哈希表"]),
  createProblem(739, "每日温度", "daily-temperatures", "中等", ["栈", "单调栈"]),
  createProblem(763, "划分字母区间", "partition-labels", "中等", ["哈希表", "双指针", "贪心"]),
  createProblem(994, "腐烂的橘子", "rotting-oranges", "中等", ["广度优先搜索", "矩阵"]),
  createProblem(1143, "最长公共子序列", "longest-common-subsequence", "中等", ["字符串", "动态规划"]),
] as const satisfies readonly LeetCodeProblem[];

export const LEETCODE_HOT_100_TOTAL = LEETCODE_HOT_100_PROBLEMS.length;
